-- V1__initial_schema.sql: Initial schema for Việt Phục Studio

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) DEFAULT 'USER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE outfits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    occasion VARCHAR(50) NOT NULL,
    region VARCHAR(50) NOT NULL,
    style VARCHAR(50) NOT NULL,
    primary_garment VARCHAR(100) NOT NULL,
    colors_json TEXT,
    accessories_json TEXT,
    cultural_notes TEXT,
    status VARCHAR(20) DEFAULT 'SAVED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_outfits_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_outfits_user_id ON outfits(user_id);
CREATE INDEX idx_users_username ON users(username);
