-- V2__create_cultural_tables.sql: Cultural Encyclopedia Tables & Seed Data

CREATE TABLE cultural_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    region VARCHAR(50),
    historical_period VARCHAR(100),
    description TEXT NOT NULL,
    significance TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cultural_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cultural_item_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    publisher VARCHAR(150),
    url VARCHAR(500),
    CONSTRAINT fk_cultural_sources_item FOREIGN KEY (cultural_item_id) REFERENCES cultural_items (id) ON DELETE CASCADE
);

CREATE INDEX idx_cultural_items_category ON cultural_items(category);
CREATE INDEX idx_cultural_items_name ON cultural_items(name);

-- Seed Data (Historical Authentic Records)
INSERT INTO cultural_items (id, name, category, region, historical_period, description, significance) VALUES
(1, 'Áo Nhật Bình', 'GARMENT', 'Miền Trung (Hue)', 'Triều Nguyễn (1802 - 1945)', 
'Áo Nhật Bình là trang trọng lễ phục của Hoàng hậu, Công chúa và Mệnh phụ triều Nguyễn. Thiết kế đặc trưng với dải cổ áo hình chữ nhật dệt thêu hoa văn phượng hoàng và ngũ hành.', 
'Biểu tượng của quyền lực đài các, trật tự triều chính và tính thẩm mỹ đỉnh cao trong y phục triều đình Huế.'),

(2, 'Áo Giao Lĩnh', 'GARMENT', 'Toàn quốc', 'Lý - Trần - Lê (Thế kỷ XI - XVIII)', 
'Áo Giao Lĩnh có hai vạt áo vắt chéo nhau trước ngực. Đây là trang phục kinh điển cổ xưa nhất của người Việt trước khi Áo Ngũ Thân xuất hiện.', 
'Thể hiện nguồn gốc y phục lâu đời và nét đẹp mộc mạc, tôn nghiêm của các triều đại phong kiến Việt Nam.'),

(3, 'Áo Tấc (Áo Ngũ Thân Lễ Phục)', 'GARMENT', 'Miền Bắc & Miền Trung', 'Thế kỷ XVIII - XX', 
'Áo Tấc là biến thể tay thụt rộng của Áo Ngũ Thân, dệt từ lụa tơ tằm, mặc kèm quần lụa trắng/thâm và khăn đóng đen.', 
'Đại diện cho phong thái nho nhã, tôn kính trong các buổi nghi lễ, dâng hương, đi chùa và mừng thọ.'),

(4, 'Mấn & Khăn Đóng Truyền Thống', 'ACCESSORY', 'Toàn quốc', 'Thế kỷ XIX - Hiện đại', 
'Vật dụng đội đầu trang trọng tôn vinh mái tóc và nét diện mạo của nam nữ người Việt khi mặc trang phục truyền thống.', 
'Giúp nâng cao vóc dáng, hoàn thiện sự chỉnh chu và tôn vinh nghi lễ cổ truyền.');

INSERT INTO cultural_sources (cultural_item_id, title, publisher, url) VALUES
(1, 'Khâm Định Đại Nam Hội Điển Sự Lệ', 'Quốc Sử Quán Triều Nguyễn', 'https://vi.wikipedia.org/wiki/Nhat_Binh'),
(2, 'Trang phục Việt Nam qua các thời kỳ', 'NXB Văn Hóa Thông Tin', 'https://vi.wikipedia.org/wiki/Trang_phuc_Viet_Nam'),
(3, 'Ngàn Năm Áo Mũ', 'Trần Quang Đức - NXB Thế Giới', 'https://vi.wikipedia.org/wiki/Ao_dinh'),
(4, 'Nghi lễ trang phục cổ truyền Việt Nam', 'NXB Hà Nội', 'https://vi.wikipedia.org/wiki/Khan_dong');
