-- V3__create_rental_tables.sql: Rental Locator Tables & Seed Data

CREATE TABLE rental_providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(50) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    phone VARCHAR(30),
    website VARCHAR(255),
    is_demo_data BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rental_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price_per_day DECIMAL(10,2) NOT NULL,
    availability_status VARCHAR(20) DEFAULT 'AVAILABLE',
    CONSTRAINT fk_rental_items_provider FOREIGN KEY (provider_id) REFERENCES rental_providers (id) ON DELETE CASCADE
);

CREATE INDEX idx_rental_providers_city ON rental_providers(city);

-- Seed Demo Data
INSERT INTO rental_providers (id, name, address, city, latitude, longitude, phone, website, is_demo_data) VALUES
(1, 'Việt Phục Cố Đô Studio', '24 Nguyễn Huệ, Phường Vĩnh Ninh', 'Thừa Thiên Huế', 16.4637, 107.5909, '0905 123 456', 'https://vietphuccodo.demo', TRUE),
(2, 'Tiệm Phục Cổ Thăng Long', '15 Hàng Gai, Quận Hoàn Kiếm', 'Hà Nội', 21.0313, 105.8524, '0912 987 654', 'https://thanglongphucco.demo', TRUE),
(3, 'Sài Gòn Y Phục Quán', '88 Lê Thị Riêng, Quận 1', 'TP. Hồ Chí Minh', 10.7719, 106.6923, '0988 333 777', 'https://saigonyphuc.demo', TRUE);

INSERT INTO rental_items (provider_id, name, category, price_per_day, availability_status) VALUES
(1, 'Áo Nhật Bình Hoàng Gia Huế (Gấm thêu phượng)', 'Áo Nhật Bình', 350000.00, 'AVAILABLE'),
(1, 'Áo Tấc Nho Sinh (Lụa Hà Đông)', 'Áo Tấc', 250000.00, 'AVAILABLE'),
(2, 'Áo Giao Lĩnh Lê Sơ cổ truyền', 'Áo Giao Lĩnh', 300000.00, 'AVAILABLE'),
(2, 'Áo Dài Ngũ Thân Tân Thời Nam/Nữ', 'Áo Dài', 200000.00, 'AVAILABLE'),
(3, 'Áo Bá Chế Nam Bộ & Khăn Rằn', 'Trang Phục Nam Bộ', 180000.00, 'AVAILABLE'),
(3, 'Bộ Nhật Bình Mệnh Phụ Kim Thêu', 'Áo Nhật Bình', 400000.00, 'AVAILABLE');
